---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 'https://api.stackbit.com/project/5d3a3bb36caf840011db473d/webhook/forestry'
sections:
  - type: document
    label: Home
    path: src/pages/index.md
    templates:
      - home
  - type: document
    label: About
    path: src/pages/about/index.md
    templates:
      - about
  - type: document
    label: Products
    path: src/pages/products/index.md
    templates:
      - products
  - type: directory
    path: src/pages/blog
    match: '**/*'
    label: Blog posts
    create: all
    templates:
      - blog
upload_dir: static/img
public_path: /img
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
