---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/5d3a3bb36caf840011db473d/webhook/forestry
sections:
- type: document
  path: src/pages/index.md
  label: Home
  templates:
  - home
- type: document
  path: src/pages/about/index.md
  label: About
  templates:
  - about
- type: document
  path: src/pages/products/index.md
  label: Products
  templates:
  - products
- type: directory
  path: src/pages/blog
  label: Blog posts
  create: all
  match: "**/*"
  templates:
  - blog
upload_dir: ''
public_path: https://res.cloudinary.com/glinkaco/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
instant_preview: true
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
  publish_command: gatsby build
  output_directory: public
  preview_command: gatsby build
